name: Continuous Integration

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm install --no-audit
      
      # - name: Run security audit
      #   run: npm audit
      
      - name: Lint
        run: npm run lint
      
      - name: Run unit tests
        run: npm run test:unit
      
      - name: Build
        run: npm run build
      
      - name: Start the application
        run: npm run preview &
        env:
          VITE_FIREBASE_API_KEY: ${{ secrets.VITE_FIREBASE_API_KEY }}
          VITE_FIREBASE_AUTH_DOMAIN: ${{ secrets.VITE_FIREBASE_AUTH_DOMAIN }}
          VITE_FIREBASE_PROJECT_ID: ${{ secrets.VITE_FIREBASE_PROJECT_ID }}
          VITE_FIREBASE_STORAGE_BUCKET: ${{ secrets.VITE_FIREBASE_STORAGE_BUCKET }}
          VITE_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.VITE_FIREBASE_MESSAGING_SENDER_ID }}
          VITE_FIREBASE_APP_ID: ${{ secrets.VITE_FIREBASE_APP_ID }}
          VITE_FIREBASE_MEASUREMENT_ID: ${{ secrets.VITE_FIREBASE_MEASUREMENT_ID }}
      
      - name: Run ZAP Scan
        uses: zaproxy/action-api-scan@v0.4.0
        with:
          target: http://localhost:4173
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a -z "config.disablekey=true"'
          allow_issue_writing: false
          fail_action: false
          issue_title: ''
          format: openapi
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Ensure Report Directory Exists
        run: mkdir -p zap_results
      
      - name: Check ZAP Scan Results
        run: |
          if [ -f "report_json.json" ]; then
            echo "ZAP scan completed successfully"
            cat report_json.json
            mv report_json.json zap_results/  # Move report to correct folder
          else
            echo "ZAP scan failed to generate report"
            exit 1
          fi
      
      - name: Upload ZAP Scan Results
        uses: actions/upload-artifact@v4
        with:
          name: zap-scan-results
          path: zap_results/
      
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }} 